title = "HyperParameters"

[paths]
output = "../dataset/nus/"

[occupancy]
path = "../dataset/nus/bbox/"


[lidar]
lower_fov = -30.0
upper_fov = 10.0
sets = 1
num = [1]
channels = [32.0]
GLOBAL_HEIGHT_POS = 1.8

x = [
    [0.0]
]

y = [
    [0.0]
]

z = [
    [1.8]
]

roll = [
    [0.0]
]

pitch = [
    [0.0]
]


[camera]

T_CAM_FRONT = [0.0, 0.0, 1.6]
R_CAM_FRONT = [0.0, 0.0, 0.0]
FOV_CAM_FRONT = 60.0


T_CAM_FRONT_LEFT = [0.0, 0.0, 1.6]
R_CAM_FRONT_LEFT = [0.0, 0.0, -60.0]
FOV_CAM_FRONT_LEFT = 60.0


T_CAM_FRONT_RIGHT = [0.0, 0.0, 1.6]
R_CAM_FRONT_RIGHT = [0.0, 0.0, 60.0]
FOV_CAM_FRONT_RIGHT = 60.0


T_CAM_BACK = [0.0, 0.0, 1.6]
R_CAM_BACK = [0.0, 0.0, 180.0]
FOV_CAM_BACK = 60.0


T_CAM_BACK_LEFT = [0.0, 0.0, 1.6]
R_CAM_BACK_LEFT = [0.0, 0.0, -120.0]
FOV_CAM_BACK_LEFT = 60.0


T_CAM_BACK_RIGHT = [0.0, 0.0, 1.6]
R_CAM_BACK_RIGHT = [0.0, 0.0, 120.0]
FOV_CAM_BACK_RIGHT = 60.0

