title = "HyperParameters"

[paths]
output = "../dataset/nus/"

[occupancy]
path = "../dataset/nus/bbox/"


[lidar]

sets = 1
num = [2]

channels = [
    [32.0, 32.0]
]

lower_fov = [
    [-8.52, -24.8]
]

upper_fov = [
    [2.0, -8.94]
]

lidar_range_in_meters = [
    [200.0, 200.0]
]

rotation_frequency = [
    [20.0, 20.0]
]

points_per_channel = [
    [14_400, 14_400]
]

GLOBAL_HEIGHT_POS = 1.8

# 1x64

x = [
    [0.0, 0.0]
]

y = [
    [0.0, 0.0]
]

z = [
    [2.0, 2.0]
]

roll = [
    [0.0, 0.0]
]

pitch = [
    [0.0, 0.0]
]


[camera]

T_CAM_FRONT = [0.0, 0.0, 1.6]
R_CAM_FRONT = [0.0, 0.0, 0.0]
FOV_CAM_FRONT = 60.0


T_CAM_FRONT_LEFT = [0.0, 0.0, 1.6]
R_CAM_FRONT_LEFT = [0.0, 0.0, -60.0]
FOV_CAM_FRONT_LEFT = 60.0


T_CAM_FRONT_RIGHT = [0.0, 0.0, 1.6]
R_CAM_FRONT_RIGHT = [0.0, 0.0, 60.0]
FOV_CAM_FRONT_RIGHT = 60.0


T_CAM_BACK = [0.0, 0.0, 1.6]
R_CAM_BACK = [0.0, 0.0, 180.0]
FOV_CAM_BACK = 60.0


T_CAM_BACK_LEFT = [0.0, 0.0, 1.6]
R_CAM_BACK_LEFT = [0.0, 0.0, -120.0]
FOV_CAM_BACK_LEFT = 60.0


T_CAM_BACK_RIGHT = [0.0, 0.0, 1.6]
R_CAM_BACK_RIGHT = [0.0, 0.0, 120.0]
FOV_CAM_BACK_RIGHT = 60.0
