title = "HyperParameters"

[paths]
output = "../dataset/nus/"

[occupancy]
path = "../dataset/nus/bbox/"


[lidar]
lower_fov = -18.0
upper_fov = 2.0
sets = 1
num = [2]
channels = [32.0]

x = [
    [0.4, -1.2]
]

y = [
    [0.0, 0.0]
]

z = [
    [1.50, 1.50]
]

roll = [
    [0.0, 0.0]
]

pitch = [
    [0.0, 0.0]
]


[camera]

T_CAM_FRONT = [-1.2, 0.4, 1.5]
R_CAM_FRONT = [0.0, 0.0, 150.0]


T_CAM_FRONT_LEFT = [0.2, -0.4, 1.5]
R_CAM_FRONT_LEFT = [0.0, 0.0, -30.0]


T_CAM_FRONT_RIGHT = [0.2, 0.4, 1.5]
R_CAM_FRONT_RIGHT = [0.0, 0.0, 30.0]


T_CAM_BACK = [-1.2, -0.4, 1.5]
R_CAM_BACK = [0.0, 0.0, -150.0]


T_CAM_BACK_LEFT = [-0.4, -0.6, 1.5]
R_CAM_BACK_LEFT = [0.0, 0.0, -90.0]


T_CAM_BACK_RIGHT = [-0.4, 0.6, 1.5]
R_CAM_BACK_RIGHT = [0.0, 0.0, 90.0]

